Repository FelixAllard/Haven-Labs, pull requests merged in 2025-01, with the labels that each got.

#28 Feat/(felix) 32 owner create and send emails by choosing a format
  .dockerignore
  .github/PULL_REQUEST_TEMPLATE.md
  Api-Gateway/Api-Gateway.csproj
  Api-Gateway/Dockerfile
  Api-Gateway/Program.cs
  Api-Gateway/Services/ServiceAuthController.cs
  Api-Gateway/Services/ServiceDraftOrderController.cs
  Api-Gateway/Services/ServiceOrderController.cs
  Api-Gateway/Services/ServiceProductController.cs
  ApiWebAuth/ApiWebAuth.csproj
  ApiWebAuth/Dockerfile
  ApiWebAuth/Program.cs
  Haven-Lab.sln
  Shopify-Api/Dockerfile
  Shopify-Api/Program.cs
  Shopify-Api/Shopify-Api.csproj
  compose.yaml
  front-end/Dockerfile
Labels: enhancement, feat

#31 Feat/(alex) 72 global and home UI
  PlaywrightTesting/tests/SendEmailWithTemplate.spec.ts
  PlaywrightTesting/tests/Update-product-page.spec.ts
  data/init.d/appointment_table.sql
  front-end/package-lock.json
  front-end/package.json
  front-end/src/AboutUs/AboutUs.js
  front-end/src/App.js
  front-end/src/Fonts/BodoniModa/BodoniModa_28pt-Bold.ttf
  front-end/src/Fonts/BodoniModa/BodoniModa_28pt-BoldItalic.ttf
  front-end/src/Fonts/BodoniModa/BodoniModa_28pt-Medium.ttf
  front-end/src/Fonts/BodoniModa/BodoniModa_28pt-MediumItalic.ttf
  front-end/src/Fonts/Inter/Inter_28pt-Bold.ttf
  front-end/src/Fonts/Inter/Inter_28pt-BoldItalic.ttf
  front-end/src/Fonts/Inter/Inter_28pt-Medium.ttf
  front-end/src/Fonts/Inter/Inter_28pt-MediumItalic.ttf
  front-end/src/Fonts/Inter/Inter_28pt-Thin.ttf
  front-end/src/Fonts/Inter/Inter_28pt-ThinItalic.ttf
  front-end/src/Footer/Footer.css
  front-end/src/NavBar/NavBar.css
  front-end/src/NavBar/Navbar.js
  front-end/src/Pages/AboutUs/AboutUs.js
  front-end/src/Pages/Admin/Product/UpdateProductPage.js
  front-end/src/Pages/Appointments/Appointments.js
  front-end/src/Pages/Cart/Cart.js
  front-end/src/Pages/Email/EmailSendPage.js
  front-end/src/Pages/Home/Assets/arrow.png
  front-end/src/Pages/Home/Assets/placeholder.png
  front-end/src/Pages/Home/Assets/wavesloop.mp4
  front-end/src/Pages/Home/Home.css
  front-end/src/Pages/Home/Home.js
  front-end/src/Pages/Orders/OrderDetail.js
  front-end/src/Pages/Orders/Orders.js
  front-end/src/Pages/Products/ProductDetailPage.js
  front-end/src/Pages/Products/ProductsPage.css
  front-end/src/Pages/Products/ProductsPage.js
  front-end/src/Shared/HavenLab-Logo2.0-blanc.svg
  front-end/src/Shared/Logo.svg
  front-end/src/Shared/back1.jpg
  front-end/src/Shared/fonts.css
  front-end/src/Shared/global.css
Labels: enhancement

#35 Feat/(justin) 49 owner manage appointments
  Api-Gateway/Controller/ProxyAppointmentController.cs
  Api-Gateway/Models/Appointment.cs
  Api-Gateway/Services/ServiceAppointmentsController.cs
  AppointmentsService/Controllers/AppointmentController.cs
  PlaywrightTesting/tests/Appointment-getAll-andCreate.spec.ts
  TestingProject/Api-Gateway/Controller/ProxyAppointmentControllerTest.cs
  TestingProject/Api-Gateway/Services/ServiceAppointmentControllerTest.cs
  TestingProject/AppointmentsService/Controllers/AppointmentControllerTest.cs
  front-end/src/App.js
  front-end/src/Pages/Appointments/AppointmentCreate.js
  front-end/src/Pages/Appointments/AppointmentDetails.js
  front-end/src/Pages/Appointments/AppointmentUpdate.js
  front-end/src/Pages/Appointments/Appointments.js
Labels: enhancement, feat

#39 Feat/(felix) 73 ci cd deployment
  .github/workflows/startCD.yml
  Api-Gateway/Program.cs
  AppointmentsService/Program.cs
  AppointmentsService/appsettings.json
  PlaywrightTesting/tests/SendEmailWithTemplate.spec.ts
  front-end/.env.development
  front-end/.env.production
  front-end/src/App.js
  front-end/src/Pages/Admin/Authentification/OwnerLogin.js
  front-end/src/Pages/Admin/Product/AddProductPage.js
  front-end/src/Pages/Admin/Product/UpdateProductPage.js
  front-end/src/Pages/Appointments/AppointmentCreate.js
  front-end/src/Pages/Appointments/AppointmentDetails.js
  front-end/src/Pages/Appointments/AppointmentUpdate.js
  front-end/src/Pages/Appointments/Appointments.js
  front-end/src/Pages/Cart/Cart.js
  front-end/src/Pages/Email/EmailSendPage.js
  front-end/src/Pages/Home/Home.js
  front-end/src/Pages/Orders/OrderDetail.js
  front-end/src/Pages/Orders/OrderUpdatePage.js
  front-end/src/Pages/Orders/Orders.js
  front-end/src/Pages/Products/ProductDetailPage.js
  front-end/src/Pages/Products/ProductsPage.js
  import_and_reset.bat
  launch.bat
Labels: documentation, enhancement, Ci Cd

#40 Fixed CORS issue
  Api-Gateway/Program.cs
Labels: bug

#44 Revert "Feat/(regine) 66 manage order final UI"
  Api-Gateway/Program.cs
  front-end/src/Pages/Email/EmailSendPage.js
  front-end/src/Pages/Orders/Order.css
  front-end/src/Pages/Orders/OrderDetail.css
  front-end/src/Pages/Orders/OrderDetail.js
  front-end/src/Pages/Orders/Orders.js
  front-end/src/Pages/Promos/PriceRuleDetail.js
Labels: bug

#45 Fixed The problem!
  AppointmentsService/AppointmentsService.csproj
  AppointmentsService/Program.cs
  compose.yaml
  front-end/src/Pages/Email/EmailSendPage.js
  front-end/src/Pages/Home/Home.js
  front-end/src/Pages/Promos/PriceRuleDetail.js
  front-end/src/Pages/Promos/PriceRules.js
Labels: bug, documentation, Ci Cd

#48 Feat/(felix) 82 owner manager email templates
  Api-Gateway/Controller/ProxyEmailApiController.cs
  Api-Gateway/Controller/ProxyTemplateController.cs
  Api-Gateway/Models/EmailStringContainsPlaceholder.cs
  Api-Gateway/Models/EmailTemplate.cs
  Api-Gateway/Models/Template.cs
  Api-Gateway/Models/TemplateRequiredFieldNotSet.cs
  Api-Gateway/Program.cs
  Api-Gateway/Services/ServiceEmailApiController.cs
  Api-Gateway/Services/ServiceTemplateController.cs
  Email-Api/Controllers/EmailController.cs
  Email-Api/Controllers/TemplateController.cs
  Email-Api/Program.cs
  Email-Api/SRC/Exceptions/TemplatesWithIdenticalNamesFound.cs
  Email-Api/SRC/Model/Template.cs
  Email-Api/SRC/Service/ITemplateManager.cs
  Email-Api/SRC/Service/ITemplateService.cs
  Email-Api/SRC/Service/TemplateManager.cs
  Email-Api/SRC/Service/TemplateService.cs
  PlaywrightTesting/tests/SendEmailWithTemplate.spec.ts
  TestingProject/Api-Gateway/Controller/ProxyTemplateControllerTest.cs
  TestingProject/Api-Gateway/Services/ServiceEmailApiControllerTest.cs
  TestingProject/Api-Gateway/Services/ServiceTemplateControllerTest.cs
  TestingProject/Email-Api/Controllers/TemplateControllerTest.cs
  TestingProject/Email-Api/SRC/Exceptions/TemplatesWithIdenticalNamesFoundTest.cs
  TestingProject/Email-Api/SRC/Model/TemplateTest.cs
  TestingProject/Email-Api/SRC/Service/TemplateManagerTest.cs
  TestingProject/Email-Api/SRC/Service/TemplateServiceTest.cs
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.js
  front-end/src/Pages/Email/EmailPage.jsx
  front-end/src/Pages/Email/EmailSendPage.js
  front-end/src/Pages/Email/Template/AddTemplatePage.js
  front-end/src/Pages/Email/Template/ModifyTemplatePage.js
  front-end/src/Pages/Email/Template/TemplateActions.js
  front-end/src/Pages/Email/Template/TemplateList.js
  front-end/src/Pages/Email/Template/TemplateManager.js
  front-end/src/Pages/Home/Home.js
Labels: bug, documentation, enhancement, feat
