Repository FelixAllard/Haven-Labs, pull requests merged in 2025-02, with the labels that each got.

#50 Feat/(justin) owner can search for appointments
  Api-Gateway/Controller/ProxyAppointmentController.cs
  Api-Gateway/Models/AppointmentSearchArguments.cs
  Api-Gateway/Services/ServiceAppointmentsController.cs
  AppointmentsService/Controllers/AppointmentController.cs
  AppointmentsService/Models/AppointmentSearchArguments.cs
  PlaywrightTesting/tests/Appointment-getAll-andCreate.spec.ts
  PlaywrightTesting/tests/create-product-page.spec.ts
  TestingProject/Api-Gateway/Controller/ProxyAppointmentControllerTest.cs
  TestingProject/Api-Gateway/Services/ServiceAppointmentControllerTest.cs
  TestingProject/AppointmentsService/Controllers/AppointmentControllerTest.cs
  front-end/src/Pages/Appointments/Appointments.css
  front-end/src/Pages/Appointments/Appointments.js
  front-end/src/Pages/Orders/Orders.js
  front-end/src/Pages/Products/ProductsPage.js
  front-end/src/Pages/Promos/PriceRules.js
Labels: enhancement, feat

#52 Bug/(justin) authentification should communicate with backend on every request
  Api-Gateway/Controller/ProxyAuthController.cs
  Api-Gateway/Services/ServiceAuthController.cs
  ApiWebAuth/Controllers/AccountController.cs
  ApiWebAuth/Models/Register.cs
  ApiWebAuth/Models/UserRole.cs
  ApiWebAuth/app.db
  PlaywrightTesting/tests/OwnerAuthentification.spec.ts
  TestingProject/Api-Gateway/Controller/ProxyAuthControllerTest.cs
  TestingProject/Api-Gateway/Services/ServiceAuthControllerTest.cs
  TestingProject/ApiWebAuth/Controllers/AccountControllerTest.cs
  front-end/src/AXIOS/AXIOS.js
  front-end/src/AXIOS/AuthentificationContext.js
  front-end/src/AXIOS/ProtectedRoute.js
  front-end/src/Pages/Admin/Authentification/OwnerLogin.js
Labels: bug, enhancement

#53 Feat/(felix) 29 owner can search for and see all emails sent
  Api-Gateway/Controller/ProxyEmailLogController.cs
  Api-Gateway/Program.cs
  Api-Gateway/Services/ServiceEmailLogController.cs
  ApiWebAuth/app.db
  AppointmentsService/AppointmentsService.csproj
  Email-Api/Controllers/EmailLogController .cs
  Email-Api/Email-Api.csproj
  Email-Api/Migrations/20250202213226_InitialMigrationEmailApi.Designer.cs
  Email-Api/Migrations/20250202213226_InitialMigrationEmailApi.cs
  Email-Api/Migrations/20250203020935_MigrationV2.Designer.cs
  Email-Api/Migrations/20250203020935_MigrationV2.cs
  Email-Api/Migrations/ApplicationDbContextModelSnapshot.cs
  Email-Api/Program.cs
  Email-Api/SRC/Database/ApplicationDbContext.cs
  Email-Api/SRC/Database/SentEmail.cs
  Email-Api/SRC/Service/EmailLogService.cs
  Email-Api/SRC/Service/IEmailLogService.cs
  Email-Api/SRC/Service/SmtpConnection.cs
  Email-Api/Templates/playfun.html
  Email-Api/appsettings.json
  PlaywrightTesting/tests/SendEmailWithTemplate.spec.ts
  TestingProject/Api-Gateway/Controller/ProxyEmailLogControllerTest.cs
  TestingProject/Api-Gateway/Services/ServiceEmailLogControllerTest.cs
  TestingProject/Email-Api/Controllers/EmailLogControllerTest.cs
  TestingProject/Email-Api/SRC/Database/SentEmailTest.cs
  TestingProject/Email-Api/SRC/Service/EmailLogServiceTest.cs
  TestingProject/Email-Api/SRC/Service/SmtpConnectionTest.cs
  TestingProject/TestingProject.csproj
  front-end/src/App.js
  front-end/src/Pages/Email/EmailPage.jsx
  front-end/src/Pages/Email/Logs/EmailSentPage.js
  front-end/src/Pages/Email/Template/TemplateManager.js
Labels: enhancement, feat

#60 feat/(Regine)-78- Owner - Create and edit price rules
  Api-Gateway/Controller/ProxyPromoController.cs
  Api-Gateway/Services/ServicePromoController.cs
  PlaywrightTesting/tests/add-to-cart.spec.ts
  Shopify-Api/Controllers/PromoController.cs
Labels: enhancement, feat

#66 Feat/(justin) 88 protecting backend endpoints
  Api-Gateway/Attributes/RequireAuthAttribute.cs
  Api-Gateway/Controller/ProxyAppointmentController.cs
  Api-Gateway/Controller/ProxyAuthController.cs
  Api-Gateway/Controller/ProxyEmailApiController.cs
  Api-Gateway/Controller/ProxyEmailLogController.cs
  Api-Gateway/Controller/ProxyOrderController.cs
  Api-Gateway/Controller/ProxyProductController.cs
  Api-Gateway/Controller/ProxyPromoController.cs
  Api-Gateway/Controller/ProxyTemplateController.cs
  Api-Gateway/Program.cs
  Api-Gateway/Services/ServiceAuthController.cs
  PlaywrightTesting/tests/OwnerAuthentification.spec.ts
  TestingProject/Api-Gateway/Attributes/RequireAuthAttributeTest.cs
  TestingProject/Api-Gateway/Controller/ProxyAuthControllerTest.cs
  TestingProject/Api-Gateway/Services/ServiceAppointmentControllerTest.cs
  TestingProject/Api-Gateway/Services/ServiceAuthControllerTest.cs
  front-end/src/AXIOS/AXIOS.js
  front-end/src/AXIOS/AuthentificationContext.js
  front-end/src/App.js
  front-end/src/Pages/Admin/Product/AddProductPage.js
  front-end/src/Pages/Admin/Product/UpdateProductPage.js
  front-end/src/Pages/Appointments/AppointmentCreate.js
  front-end/src/Pages/Appointments/AppointmentDetails.js
  front-end/src/Pages/Appointments/AppointmentUpdate.js
  front-end/src/Pages/Appointments/Appointments.js
  front-end/src/Pages/Cart/Cart.js
  front-end/src/Pages/Email/EmailPage.js
  front-end/src/Pages/Email/EmailSendPage.js
  front-end/src/Pages/Email/Logs/EmailSentPage.js
  front-end/src/Pages/Email/Template/AddTemplatePage.js
  front-end/src/Pages/Email/Template/ModifyTemplatePage.js
  front-end/src/Pages/Email/Template/TemplateList.js
  front-end/src/Pages/Email/Template/TemplateManager.js
  front-end/src/Pages/Home/Home.css
  front-end/src/Pages/Home/Home.js
  front-end/src/Pages/Orders/OrderDetail.js
  front-end/src/Pages/Orders/OrderUpdatePage.js
  front-end/src/Pages/Orders/Orders.js
  front-end/src/Pages/Products/ProductDetailPage.js
  front-end/src/Pages/Products/ProductsPage.js
  front-end/src/Pages/Promos/AddPriceRule.js
  front-end/src/Pages/Promos/PriceRuleDetail.js
  front-end/src/Pages/Promos/PriceRules.js
  front-end/src/Pages/Promos/UpdatePriceRule.js
Labels: enhancement, feat

#67 Feat/(felix) 102 centralize environment variable in a single env
  Api-Gateway/Api-Gateway.csproj
  Api-Gateway/Program.cs
  Api-Gateway/Services/ServiceAppointmentsController.cs
  Api-Gateway/Services/ServiceAuthController.cs
  Api-Gateway/Services/ServiceCustomerController.cs
  Api-Gateway/Services/ServiceDraftOrderController.cs
  Api-Gateway/Services/ServiceEmailApiController.cs
  Api-Gateway/Services/ServiceEmailLogController.cs
  Api-Gateway/Services/ServiceOrderController.cs
  Api-Gateway/Services/ServiceProductController.cs
  Api-Gateway/Services/ServicePromoController.cs
  Api-Gateway/Services/ServiceTemplateController.cs
  ApiWebAuth/ApiWebAuth.csproj
  ApiWebAuth/Program.cs
  AppointmentsService/Program.cs
  Deployment/.env
  Email-Api/Program.cs
  Email-Api/SRC/Service/SmtpConnection.cs
  README.md
  Shopify-Api/Program.cs
  Shopify-Api/Shopify-Api.csproj
  TestingProject/TestingProject.csproj
Labels: enhancement, Ci Cd

#70 Feat/(felix) 86 make cd easier to deploy
  AppointmentsService/Migrations/20250203211024_NewMigrationV2.Designer.cs
  AppointmentsService/Migrations/20250203211024_NewMigrationV2.cs
  Deployment/Images/AccessTokenCreation/Step1.png
  Deployment/Images/AccessTokenCreation/Step2.png
  Deployment/Images/AccessTokenCreation/Step3.png
  Deployment/Images/AccessTokenCreation/Step4.png
  Deployment/Images/AccessTokenCreation/Step5.png
  Deployment/Images/AccessTokenCreation/Step6.png
  Deployment/Images/AccessTokenCreation/Step7.png
  Deployment/Images/AccessTokenCreation/Step8.png
  Deployment/Images/AccessTokenCreation/Step9.png
  Deployment/Images/C3.png
  Deployment/ShopifySetup.md
  Deployment/TEMP/.env
  Deployment/Windows/apply_migrations.bat
  Deployment/Windows/build_solution.bat
  Deployment/Windows/check_db_connection.bat
  Deployment/Windows/check_environment.bat
  Deployment/Windows/check_specs.bat
  Deployment/Windows/generate_env.bat
  Deployment/Windows/install_ef_migration.bat
  Deployment/deployment.md
Labels: documentation, enhancement

#71 Bug/(justin) add images to the model for products
  Api-Gateway/Controller/ProxyProductController.cs
  Api-Gateway/Services/ServiceProductController.cs
  ApiWebAuth/app.db
  Shopify-Api/Controllers/ProductController.cs
  Shopify-Api/Program.cs
  Shopify-Api/Shopify-Api.csproj
  TestingProject/Api-Gateway/Controller/ProxyProductControllerTest.cs
  TestingProject/Shopify-Api/Controllers/ProductControllerTest.cs
  TestingProject/Shopify-Api/SRC/ShopifyServiceTest.cs
  front-end/package-lock.json
  front-end/package.json
  front-end/src/AXIOS/AXIOS.js
  front-end/src/Languages/i18n.js
  front-end/src/Pages/Admin/Product/AddProductPage.js
  front-end/src/Pages/Admin/Product/UpdateProductPage.js
  front-end/src/Pages/Products/ProductDetailPage.js
Labels: bug, enhancement

#73 Bug/(justin) 96 fix frontend endpoints to be admin and file structure
  Api-Gateway/Controller/ProxyAppointmentController.cs
  ApiWebAuth/app.db
  PlaywrightTesting/tests/Login-Access-And-Visible-Test.spec.ts
  PlaywrightTesting/tests/OwnerAuthentification.spec.ts
  PlaywrightTesting/tests/delete-product.spec.ts
  front-end/src/App.js
  front-end/src/NavBar/Navbar.js
  front-end/src/Pages/Admin/Appointments/AppointmentCreate.js
  front-end/src/Pages/Admin/Appointments/AppointmentDetails.js
  front-end/src/Pages/Admin/Appointments/AppointmentUpdate.js
  front-end/src/Pages/Admin/Appointments/Appointments.css
  front-end/src/Pages/Admin/Appointments/Appointments.js
  front-end/src/Pages/Admin/Authentification/OwnerLogin.js
  front-end/src/Pages/Admin/Email/EmailPage.js
  front-end/src/Pages/Admin/Email/EmailSendPage.js
  front-end/src/Pages/Admin/Email/Logs/EmailSentPage.js
  front-end/src/Pages/Admin/Email/Template/AddTemplatePage.js
  front-end/src/Pages/Admin/Email/Template/ModifyTemplatePage.js
  front-end/src/Pages/Admin/Email/Template/TemplateActions.js
  front-end/src/Pages/Admin/Email/Template/TemplateList.js
  front-end/src/Pages/Admin/Email/Template/TemplateManager.js
  front-end/src/Pages/Admin/Orders/OrderDetail.js
  front-end/src/Pages/Admin/Orders/OrderUpdatePage.js
  front-end/src/Pages/Admin/Orders/Orders.js
  front-end/src/Pages/Admin/Promos/AddPriceRule.css
  front-end/src/Pages/Admin/Promos/AddPriceRule.js
  front-end/src/Pages/Admin/Promos/PriceRuleDetail.js
  front-end/src/Pages/Admin/Promos/PriceRules.js
  front-end/src/Pages/Admin/Promos/UpdatePriceRule.css
  front-end/src/Pages/Admin/Promos/UpdatePriceRule.js
  front-end/src/Pages/Shopify/ShopifyCheckout.js
  front-end/src/Pages/Shopify/ShopifyPay.js
Labels: bug

#76 Bug/(alex) 99 cart not working on cd
  front-end/src/Pages/Cart/Cart.js
  front-end/src/Pages/Products/ProductDetailPage.js
Labels: bug
